# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieExplorerTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieExplorerTask

  target 'MovieExplorerTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieExplorerTaskUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'RealmSwift'

end
